import '@/styles/globals.css'
import { useRouter } from 'next/router'
import Head from 'next/head'
import "../../fonts/DistantGalaxy.css";

export default function App({ Component, pageProps }) {
  const router = useRouter()
  return <>
    <Head>
      <title>STAR WARS Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta charSet="utf-8" />
      <meta httpEquiv="x-ua-compatible" content="ie=edge" />
      <link rel="icon" href="/favicon.svg" />
    </Head>
    <Component key={router.asPath} {...pageProps} />
  </>
}
