import Head from 'next/head'
import Link from 'next/link'
import styled from "styled-components"

const LinkContainer = styled.div`
  position: absolute;
  bottom: 22%;
  left: 10%;
  @media (max-width: 800px) {
    left: 5%;
  }
`;

const StyledLink = styled(Link)`
  font-size: 3rem;
  text-align: center;
  color: #FFF;

  @media (max-width: 800px) {
    font-size: 2rem;
  }
`;

const Main = styled.div`
  height: 100vh;
  background-image: linear-gradient(140deg, black,black,black, black, black,black,black,blue,red);
`;


export default function Home() {
  return (
    <>
      <Head>
        <title>STAR WARS Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Main>
        <LinkContainer>
          <StyledLink href="/characters">STAR WARS <br/> CHARACTERS</StyledLink>
        </LinkContainer>
      </Main>
    </>
  )
}
